### ISSUE TITLE
Most TLDs are not supported

### ISSUE THREAD

**Issue by dschoder** [moneals/whois-parsed#2]
const data = await whois.lookup( 'sony.asia' );
const data = await whois.lookup( 'test.io' );
const data = await whois.lookup( 'test.bike' );
etc...

All these cases throw 'TLD not supported.'  In this case, could you try parsing the data with the defaultRegex and throw if there's an issue?

**Comment by moneals** [comment]
Thanks dschoder, that is an excellent suggestion. I added a "catchall" style regex that should work for many additional TLDs. I tested it successfully against the .asia, .io, and .bike TLDs you mentioned. This fix is in v1.0.8

Please raise more issues if you run across  any other TLDs that seem to fit the generic pattern but for whatever reason are not working.
